### ISSUE TITLE
can't save street network as geopackage because....

### ISSUE THREAD

**Issue by derrickburt** [HEGSRR/RPr-Kang-2020#5]
Unfortunately, the ```osmnx.io.save_graph_geopackage()``` was implemented into [version 0.12.1(2020-05-01)](https://github.com/gboeing/osmnx/blob/main/CHANGELOG.md) and we are using osmnx==0.11.4.

We could, however, export the graph edges and nodes as a shapefile with the ```osmnx.io.save_graph_shapefile``` if you think that is worth it.

**Comment by derrickburt** [comment]
Also, I'm assuming we cannot update the python libraries in the cybergisx environment?

**Comment by josephholler** [comment]
save this thought until CyberGISX supports different package versions
